from __future__ import annotations

from typing import Protocol


class RobotAPI(Protocol):
    """Directional control interface for the hexapod."""

    def forward(self, speed: float) -> None: ...
    def backward(self, speed: float) -> None: ...
    def turn_left(self, rate: float) -> None: ...
    def turn_right(self, rate: float) -> None: ...
    def strafe_left(self, speed: float) -> None: ...
    def strafe_right(self, speed: float) -> None: ...
    def stop(self) -> None: ...
    def set_velocity(self, v: float) -> None: ...
    def set_gait(self, name: str) -> None: ...
    def set_pose(self, **kwargs) -> None: ...
