# Navigation defaults
lookahead_m: 0.6
safety_radius_m: 0.4
nav_rate_hz: 10
vel_min: 0.05
vel_max: 0.20
heading_deadband_deg: 10
turn_rate_max_dps: 45

uart:
    timeout_s: 2.0

mavlink:
    enabled: true
    bind_host: "0.0.0.0"
    bind_port: 14550
    system_id: 1
    component_id: 1
    heartbeat_rate_hz: 1.0
    telemetry_rate_hz: 2.0
    auto_request_mission: true
